#!/bin/bash
#This script simply loads ORCA 4.2.1
#loading the ORCA module directly is useful in situations when you want to use software that comes packaged with ORCA, such as orca_plot, orca_mapspc, orca_pltvib, orca_loc, etc.
module load nixpkgs/16.09
module load gcc/7.3.0
module load openmpi/3.1.4
module load orca/4.2.1
echo loaded orca/4.2.1

